# Generated by Django 3.1.1 on 2020-10-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
