# Generated by Django 3.1.1 on 2020-10-19 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0003_auto_20201007_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='client',
            name='purchase_date',
            field=models.CharField(max_length=30),
        ),
    ]
