# Generated by Django 3.1.1 on 2020-10-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0006_auto_20201019_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
