# Generated by Django 3.1.1 on 2020-10-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0007_auto_20201019_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
