# Generated by Django 3.1.1 on 2020-11-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0012_client_sll_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='time_spent',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
