# Generated by Django 3.1.1 on 2020-11-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0016_auto_20201107_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sll_expiry_date',
            field=models.DateField(null=True),
        ),
    ]
