# Generated by Django 3.1.1 on 2020-11-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0018_auto_20201108_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='purchase_date',
            field=models.DateField(blank=True, default='<jamming-date>', null=True),
        ),
    ]
