# Generated by Django 3.1.1 on 2020-11-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0019_auto_20201108_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
